/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QScrollBar>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLineEdit *lineEdit_username;
    QLineEdit *lineEdit_password;
    QLabel *label;
    QLabel *label_2;
    QPushButton *connecter;
    QLabel *label_3;
    QLabel *label_10;
    QPushButton *quitter;
    QWidget *page_3;
    QTabWidget *impression_badges;
    QWidget *tab_3;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QPushButton *pushButton_6;
    QLabel *label_7;
    QLabel *label_11;
    QWidget *tab;
    QLabel *label_5;
    QLabel *label_6;
    QLineEdit *le_id;
    QPushButton *pb_ajouter;
    QPushButton *pb_modifier;
    QPushButton *pb_afficher;
    QLabel *label_8;
    QLabel *label_9;
    QLineEdit *le_nom;
    QLineEdit *le_prenom;
    QLineEdit *le_annees_naiss;
    QLabel *label_12;
    QLineEdit *le_nationalite;
    QPushButton *pb_importer;
    QLabel *label_13;
    QLineEdit *le_type_sport;
    QLabel *label_14;
    QTableView *tab_joueur;
    QPushButton *export_pdf;
    QPushButton *calcul_score;
    QComboBox *comboBox_2;
    QPushButton *pb_supprimer;
    QRadioButton *trier_prenom;
    QRadioButton *trier_annees;
    QRadioButton *trier_score;
    QLineEdit *lineEdit_5;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *le_equipe;
    QLineEdit *le_score;
    QLineEdit *le_eq;
    QLabel *label_18;
    QLabel *label_score;
    QLabel *label_pdf;
    QPushButton *pushButton_7;
    QPushButton *ajout_imag;
    QPushButton *deconnexion;
    QWidget *page_4;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QLabel *label_19;
    QPushButton *qb_ajouter;
    QPushButton *pb_supp;
    QLabel *label_20;
    QLineEdit *le_horaire;
    QLineEdit *le_duree;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *le_Num;
    QLabel *label_23;
    QPushButton *exporter;
    QLabel *label_24;
    QLineEdit *le_type;
    QTableView *tab_spec;
    QLabel *label_25;
    QLabel *label_26;
    QRadioButton *trie_horaire;
    QRadioButton *trie_duree;
    QRadioButton *trie_type;
    QComboBox *comboBox;
    QPushButton *pushButton_9;
    QLineEdit *lineEdit_6;
    QPushButton *pushButton_10;
    QLineEdit *le_aff;
    QLabel *label_pic_2;
    QPushButton *deconnexion_1;
    QWidget *page_5;
    QTabWidget *tabWidget_2;
    QWidget *tab_4;
    QLabel *label_27;
    QLineEdit *le_num;
    QLineEdit *le_ref;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLineEdit *le_date;
    QSpinBox *spinBox;
    QPushButton *QR_code;
    QLineEdit *le_ref_supp;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *recher_edit;
    QTableView *tab_ticket;
    QRadioButton *trier_nom;
    QRadioButton *trier_num;
    QRadioButton *trier_datee;
    QComboBox *comboBox_modifier_ref;
    QLabel *label_pic_3;
    QLineEdit *le_QR_2;
    QPushButton *lineEdit_7;
    QPushButton *pb_upload;
    QPushButton *ajouterT;
    QLineEdit *le_nomT;
    QLineEdit *le_prenomT;
    QPushButton *afficherT;
    QPushButton *modifierT;
    QPushButton *supprimerT;
    QPushButton *exporter_pdfT;
    QPushButton *deconnexion_3;
    QWidget *tab_5;
    QLabel *label_34;
    QPushButton *pushButton_stat;
    QLabel *label_stat;
    QWidget *page_6;
    QTabWidget *tabWidget_3;
    QWidget *tab_6;
    QPushButton *pb_ajouter_3;
    QPushButton *pb_modifier_3;
    QPushButton *pb_supprimer_3;
    QPushButton *pb_afficher_3;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *le_equipe1;
    QLineEdit *le_equipe2;
    QLabel *le_numero_2;
    QLineEdit *le_numero;
    QLineEdit *le_reference;
    QLabel *label_37;
    QTableView *tabCompetition;
    QComboBox *comboBox_3;
    QRadioButton *trierTemps;
    QRadioButton *trier_score_2;
    QRadioButton *trier_equipe;
    QTableView *tabrecherche;
    QLineEdit *recherche;
    QLabel *score;
    QLabel *mail;
    QLineEdit *le_score_2;
    QLineEdit *le_mail;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QLineEdit *le_temps;
    QLabel *temps;
    QLineEdit *rechav;
    QLabel *rechavv;
    QPushButton *deconnexion_4;
    QWidget *tab_7;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QLineEdit *lineEdit_to_email;
    QLineEdit *lineEdit_subject_email;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QTextEdit *textEdit_email;
    QWidget *page_7;
    QTabWidget *tabWidget_4;
    QWidget *tab_11;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QTableView *tableView;
    QLineEdit *enterID;
    QLineEdit *lineEdit_nom;
    QComboBox *comboBox_4;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *afficherE;
    QPushButton *modifierE;
    QPushButton *supprimerE;
    QPushButton *ajouterE;
    QLineEdit *le_idE;
    QLineEdit *le_nomE;
    QLineEdit *le_prenomE;
    QLineEdit *le_emplacementE;
    QPushButton *deconnexion_5;
    QWidget *tab_12;
    QListView *listView;
    QScrollBar *horizontalScrollBar;
    QScrollBar *verticalScrollBar;
    QLabel *label_56;
    QPushButton *pushButton_25;
    QPushButton *export_pdfE;
    QStatusBar *statusbar;
    QMenuBar *menubar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1305, 697);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(80, 30, 1141, 591));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        lineEdit_username = new QLineEdit(page);
        lineEdit_username->setObjectName(QStringLiteral("lineEdit_username"));
        lineEdit_username->setGeometry(QRect(200, 270, 411, 41));
        lineEdit_password = new QLineEdit(page);
        lineEdit_password->setObjectName(QStringLiteral("lineEdit_password"));
        lineEdit_password->setGeometry(QRect(200, 330, 411, 41));
        label = new QLabel(page);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(45, 280, 111, 20));
        label_2 = new QLabel(page);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(35, 340, 91, 20));
        connecter = new QPushButton(page);
        connecter->setObjectName(QStringLiteral("connecter"));
        connecter->setGeometry(QRect(282, 407, 151, 51));
        label_3 = new QLabel(page);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(300, 140, 181, 91));
        label_10 = new QLabel(page);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(310, 80, 101, 71));
        label_10->setStyleSheet(QStringLiteral("background-color: rgb(234, 235, 239);"));
        label_10->setPixmap(QPixmap(QString::fromUtf8("../../Bureau/ACCOUNT.png")));
        label_10->setScaledContents(true);
        quitter = new QPushButton(page);
        quitter->setObjectName(QStringLiteral("quitter"));
        quitter->setGeometry(QRect(480, 430, 93, 28));
        stackedWidget->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        impression_badges = new QTabWidget(page_3);
        impression_badges->setObjectName(QStringLiteral("impression_badges"));
        impression_badges->setGeometry(QRect(0, 10, 941, 551));
        impression_badges->setStyleSheet(QLatin1String("background-color: rgb(202, 202, 202);\n"
""));
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        lineEdit_3 = new QLineEdit(tab_3);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(230, 120, 141, 22));
        lineEdit_4 = new QLineEdit(tab_3);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(232, 150, 141, 22));
        pushButton_6 = new QPushButton(tab_3);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(280, 180, 51, 21));
        label_7 = new QLabel(tab_3);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(0, -5, 501, 361));
        label_7->setPixmap(QPixmap(QString::fromUtf8("../../Bureau/v.png")));
        label_7->setScaledContents(true);
        label_11 = new QLabel(tab_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(280, 60, 51, 51));
        label_11->setStyleSheet(QStringLiteral("background-color: rgb(234, 235, 239);"));
        label_11->setPixmap(QPixmap(QString::fromUtf8("../../Bureau/ACCOUNT.png")));
        label_11->setScaledContents(true);
        impression_badges->addTab(tab_3, QString());
        lineEdit_3->raise();
        lineEdit_4->raise();
        pushButton_6->raise();
        label_11->raise();
        label_7->raise();
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 30, 56, 16));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(30, 70, 56, 16));
        le_id = new QLineEdit(tab);
        le_id->setObjectName(QStringLiteral("le_id"));
        le_id->setGeometry(QRect(150, 30, 113, 22));
        pb_ajouter = new QPushButton(tab);
        pb_ajouter->setObjectName(QStringLiteral("pb_ajouter"));
        pb_ajouter->setGeometry(QRect(340, 30, 93, 28));
        pb_ajouter->setStyleSheet(QStringLiteral(""));
        pb_modifier = new QPushButton(tab);
        pb_modifier->setObjectName(QStringLiteral("pb_modifier"));
        pb_modifier->setGeometry(QRect(340, 90, 93, 28));
        pb_modifier->setStyleSheet(QStringLiteral(""));
        pb_afficher = new QPushButton(tab);
        pb_afficher->setObjectName(QStringLiteral("pb_afficher"));
        pb_afficher->setGeometry(QRect(340, 210, 93, 28));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 110, 56, 16));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(30, 160, 121, 16));
        le_nom = new QLineEdit(tab);
        le_nom->setObjectName(QStringLiteral("le_nom"));
        le_nom->setGeometry(QRect(150, 70, 113, 22));
        le_prenom = new QLineEdit(tab);
        le_prenom->setObjectName(QStringLiteral("le_prenom"));
        le_prenom->setGeometry(QRect(150, 110, 113, 22));
        le_annees_naiss = new QLineEdit(tab);
        le_annees_naiss->setObjectName(QStringLiteral("le_annees_naiss"));
        le_annees_naiss->setGeometry(QRect(150, 160, 113, 22));
        label_12 = new QLabel(tab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 200, 61, 16));
        le_nationalite = new QLineEdit(tab);
        le_nationalite->setObjectName(QStringLiteral("le_nationalite"));
        le_nationalite->setGeometry(QRect(150, 200, 113, 22));
        pb_importer = new QPushButton(tab);
        pb_importer->setObjectName(QStringLiteral("pb_importer"));
        pb_importer->setGeometry(QRect(340, 270, 93, 28));
        label_13 = new QLabel(tab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 240, 91, 16));
        le_type_sport = new QLineEdit(tab);
        le_type_sport->setObjectName(QStringLiteral("le_type_sport"));
        le_type_sport->setGeometry(QRect(150, 240, 113, 22));
        label_14 = new QLabel(tab);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(0, -20, 951, 551));
        label_14->setPixmap(QPixmap(QString::fromUtf8("../../Bureau/bb.png")));
        label_14->setScaledContents(true);
        tab_joueur = new QTableView(tab);
        tab_joueur->setObjectName(QStringLiteral("tab_joueur"));
        tab_joueur->setGeometry(QRect(480, 70, 451, 321));
        export_pdf = new QPushButton(tab);
        export_pdf->setObjectName(QStringLiteral("export_pdf"));
        export_pdf->setGeometry(QRect(720, 420, 91, 41));
        calcul_score = new QPushButton(tab);
        calcul_score->setObjectName(QStringLiteral("calcul_score"));
        calcul_score->setGeometry(QRect(610, 420, 91, 41));
        comboBox_2 = new QComboBox(tab);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(350, 71, 81, 20));
        pb_supprimer = new QPushButton(tab);
        pb_supprimer->setObjectName(QStringLiteral("pb_supprimer"));
        pb_supprimer->setGeometry(QRect(340, 150, 93, 28));
        trier_prenom = new QRadioButton(tab);
        trier_prenom->setObjectName(QStringLiteral("trier_prenom"));
        trier_prenom->setGeometry(QRect(490, 20, 101, 20));
        trier_annees = new QRadioButton(tab);
        trier_annees->setObjectName(QStringLiteral("trier_annees"));
        trier_annees->setGeometry(QRect(620, 20, 161, 20));
        trier_score = new QRadioButton(tab);
        trier_score->setObjectName(QStringLiteral("trier_score"));
        trier_score->setGeometry(QRect(800, 20, 97, 20));
        lineEdit_5 = new QLineEdit(tab);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(810, 50, 113, 22));
        label_15 = new QLabel(tab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(330, 310, 121, 181));
        label_16 = new QLabel(tab);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(30, 290, 56, 16));
        label_17 = new QLabel(tab);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(30, 330, 56, 16));
        le_equipe = new QLineEdit(tab);
        le_equipe->setObjectName(QStringLiteral("le_equipe"));
        le_equipe->setGeometry(QRect(150, 290, 113, 22));
        le_score = new QLineEdit(tab);
        le_score->setObjectName(QStringLiteral("le_score"));
        le_score->setGeometry(QRect(150, 330, 113, 22));
        le_eq = new QLineEdit(tab);
        le_eq->setObjectName(QStringLiteral("le_eq"));
        le_eq->setGeometry(QRect(600, 470, 113, 22));
        label_18 = new QLabel(tab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(520, 470, 56, 16));
        label_score = new QLabel(tab);
        label_score->setObjectName(QStringLiteral("label_score"));
        label_score->setGeometry(QRect(740, 470, 131, 31));
        label_pdf = new QLabel(tab);
        label_pdf->setObjectName(QStringLiteral("label_pdf"));
        label_pdf->setGeometry(QRect(50, 380, 151, 81));
        pushButton_7 = new QPushButton(tab);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(830, 420, 93, 28));
        ajout_imag = new QPushButton(tab);
        ajout_imag->setObjectName(QStringLiteral("ajout_imag"));
        ajout_imag->setGeometry(QRect(490, 420, 93, 28));
        deconnexion = new QPushButton(tab);
        deconnexion->setObjectName(QStringLiteral("deconnexion"));
        deconnexion->setGeometry(QRect(40, 470, 93, 28));
        impression_badges->addTab(tab, QString());
        label_14->raise();
        lineEdit_5->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        pushButton_7->raise();
        ajout_imag->raise();
        label_8->raise();
        le_id->raise();
        pb_ajouter->raise();
        pb_modifier->raise();
        pb_afficher->raise();
        le_nom->raise();
        le_prenom->raise();
        le_annees_naiss->raise();
        label_5->raise();
        le_nationalite->raise();
        pb_importer->raise();
        label_6->raise();
        le_type_sport->raise();
        tab_joueur->raise();
        export_pdf->raise();
        calcul_score->raise();
        comboBox_2->raise();
        pb_supprimer->raise();
        trier_prenom->raise();
        trier_annees->raise();
        trier_score->raise();
        label_9->raise();
        label_12->raise();
        le_equipe->raise();
        le_score->raise();
        le_eq->raise();
        label_13->raise();
        label_score->raise();
        label_pdf->raise();
        deconnexion->raise();
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        tabWidget = new QTabWidget(page_4);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(120, 60, 701, 451));
        QFont font;
        font.setFamily(QStringLiteral("Segoe UI"));
        font.setBold(false);
        font.setWeight(50);
        tabWidget->setFont(font);
        tabWidget->setStyleSheet(QLatin1String("background-color: rgb(206, 206, 206);\n"
"border-color: rgb(239, 240, 242);\n"
"background-color: rgb(239, 240, 242);\n"
"selection-color: rgb(239, 240, 242);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(6, 6, 6);\n"
"border-color: rgb(0, 0, 0);"));
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 20, 131, 16));
        label_19->setFont(font);
        label_19->setStyleSheet(QLatin1String("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(237, 238, 240);"));
        qb_ajouter = new QPushButton(tab_2);
        qb_ajouter->setObjectName(QStringLiteral("qb_ajouter"));
        qb_ajouter->setGeometry(QRect(410, 160, 81, 23));
        pb_supp = new QPushButton(tab_2);
        pb_supp->setObjectName(QStringLiteral("pb_supp"));
        pb_supp->setGeometry(QRect(520, 70, 61, 23));
        pb_supp->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_20 = new QLabel(tab_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(410, 250, 47, 14));
        QFont font1;
        font1.setFamily(QStringLiteral("Mudir MT"));
        font1.setBold(true);
        font1.setWeight(75);
        label_20->setFont(font1);
        label_20->setStyleSheet(QStringLiteral("background-color: rgb(231, 232, 236);"));
        le_horaire = new QLineEdit(tab_2);
        le_horaire->setObjectName(QStringLiteral("le_horaire"));
        le_horaire->setGeometry(QRect(390, 70, 113, 20));
        le_horaire->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";"));
        le_duree = new QLineEdit(tab_2);
        le_duree->setObjectName(QStringLiteral("le_duree"));
        le_duree->setGeometry(QRect(390, 100, 113, 20));
        le_duree->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";"));
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(340, 70, 41, 20));
        label_21->setStyleSheet(QStringLiteral("background-color: rgb(236, 237, 239);"));
        label_22 = new QLabel(tab_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(350, 100, 31, 20));
        label_22->setStyleSheet(QStringLiteral("background-color: rgb(237, 239, 242);"));
        le_Num = new QLineEdit(tab_2);
        le_Num->setObjectName(QStringLiteral("le_Num"));
        le_Num->setGeometry(QRect(390, 40, 113, 20));
        le_Num->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";"));
        label_23 = new QLabel(tab_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(350, 40, 21, 16));
        label_23->setStyleSheet(QStringLiteral("background-color: rgb(240, 241, 243);"));
        exporter = new QPushButton(tab_2);
        exporter->setObjectName(QStringLiteral("exporter"));
        exporter->setGeometry(QRect(550, 130, 75, 23));
        label_24 = new QLabel(tab_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(350, 130, 31, 16));
        le_type = new QLineEdit(tab_2);
        le_type->setObjectName(QStringLiteral("le_type"));
        le_type->setGeometry(QRect(390, 130, 113, 20));
        le_type->setStyleSheet(QStringLiteral("font: 8pt \"MS Shell Dlg 2\";"));
        tab_spec = new QTableView(tab_2);
        tab_spec->setObjectName(QStringLiteral("tab_spec"));
        tab_spec->setGeometry(QRect(10, 40, 321, 261));
        label_25 = new QLabel(tab_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(0, -7, 731, 431));
        label_25->setPixmap(QPixmap(QString::fromUtf8("../../../../bb.png")));
        label_25->setScaledContents(true);
        label_26 = new QLabel(tab_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 310, 47, 14));
        label_26->setStyleSheet(QStringLiteral("background-color: rgb(217, 221, 224);"));
        trie_horaire = new QRadioButton(tab_2);
        trie_horaire->setObjectName(QStringLiteral("trie_horaire"));
        trie_horaire->setGeometry(QRect(70, 310, 83, 18));
        trie_horaire->setStyleSheet(QStringLiteral("background-color: rgb(206, 211, 215);"));
        trie_duree = new QRadioButton(tab_2);
        trie_duree->setObjectName(QStringLiteral("trie_duree"));
        trie_duree->setGeometry(QRect(160, 310, 83, 18));
        trie_duree->setStyleSheet(QStringLiteral("background-color: rgb(217, 221, 224);"));
        trie_type = new QRadioButton(tab_2);
        trie_type->setObjectName(QStringLiteral("trie_type"));
        trie_type->setGeometry(QRect(250, 310, 83, 18));
        trie_type->setStyleSheet(QStringLiteral("background-color: rgb(211, 215, 220);"));
        comboBox = new QComboBox(tab_2);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(530, 40, 111, 22));
        pushButton_9 = new QPushButton(tab_2);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(590, 70, 61, 23));
        pushButton_9->setStyleSheet(QStringLiteral("background-color: rgb(0, 255, 0);"));
        lineEdit_6 = new QLineEdit(tab_2);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(130, 10, 201, 20));
        pushButton_10 = new QPushButton(tab_2);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(440, 350, 151, 21));
        le_aff = new QLineEdit(tab_2);
        le_aff->setObjectName(QStringLiteral("le_aff"));
        le_aff->setGeometry(QRect(460, 320, 101, 20));
        label_pic_2 = new QLabel(tab_2);
        label_pic_2->setObjectName(QStringLiteral("label_pic_2"));
        label_pic_2->setGeometry(QRect(440, 200, 141, 111));
        label_pic_2->setStyleSheet(QLatin1String("background-color: rgb(233, 234, 238);\n"
"background-color: rgb(180, 180, 180);"));
        deconnexion_1 = new QPushButton(tab_2);
        deconnexion_1->setObjectName(QStringLiteral("deconnexion_1"));
        deconnexion_1->setGeometry(QRect(20, 380, 93, 28));
        tabWidget->addTab(tab_2, QString());
        label_19->raise();
        label_20->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        pushButton_9->raise();
        lineEdit_6->raise();
        pushButton_10->raise();
        qb_ajouter->raise();
        pb_supp->raise();
        le_horaire->raise();
        le_duree->raise();
        le_Num->raise();
        exporter->raise();
        le_type->raise();
        tab_spec->raise();
        trie_horaire->raise();
        trie_duree->raise();
        trie_type->raise();
        comboBox->raise();
        le_aff->raise();
        label_pic_2->raise();
        deconnexion_1->raise();
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        tabWidget_2 = new QTabWidget(page_5);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(80, 50, 781, 501));
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_27 = new QLabel(tab_4);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 100, 56, 16));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        label_27->setFont(font2);
        le_num = new QLineEdit(tab_4);
        le_num->setObjectName(QStringLiteral("le_num"));
        le_num->setGeometry(QRect(80, 60, 113, 22));
        le_ref = new QLineEdit(tab_4);
        le_ref->setObjectName(QStringLiteral("le_ref"));
        le_ref->setGeometry(QRect(80, 20, 113, 22));
        label_28 = new QLabel(tab_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 180, 56, 16));
        label_28->setFont(font2);
        label_29 = new QLabel(tab_4);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(10, 140, 56, 16));
        label_29->setFont(font2);
        label_30 = new QLabel(tab_4);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(10, 60, 56, 16));
        label_30->setFont(font2);
        label_31 = new QLabel(tab_4);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 20, 71, 16));
        label_31->setFont(font2);
        le_date = new QLineEdit(tab_4);
        le_date->setObjectName(QStringLiteral("le_date"));
        le_date->setGeometry(QRect(80, 100, 113, 22));
        spinBox = new QSpinBox(tab_4);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(730, 330, 42, 22));
        QR_code = new QPushButton(tab_4);
        QR_code->setObjectName(QStringLiteral("QR_code"));
        QR_code->setGeometry(QRect(210, 167, 101, 31));
        le_ref_supp = new QLineEdit(tab_4);
        le_ref_supp->setObjectName(QStringLiteral("le_ref_supp"));
        le_ref_supp->setGeometry(QRect(40, 250, 191, 22));
        label_32 = new QLabel(tab_4);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(120, 230, 21, 16));
        label_33 = new QLabel(tab_4);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(40, -30, 781, 481));
        label_33->setPixmap(QPixmap(QString::fromUtf8("../../../../bb.png")));
        label_33->setScaledContents(true);
        recher_edit = new QLineEdit(tab_4);
        recher_edit->setObjectName(QStringLiteral("recher_edit"));
        recher_edit->setGeometry(QRect(420, 340, 131, 22));
        tab_ticket = new QTableView(tab_4);
        tab_ticket->setObjectName(QStringLiteral("tab_ticket"));
        tab_ticket->setGeometry(QRect(370, 90, 401, 241));
        trier_nom = new QRadioButton(tab_4);
        trier_nom->setObjectName(QStringLiteral("trier_nom"));
        trier_nom->setGeometry(QRect(650, 60, 111, 20));
        trier_num = new QRadioButton(tab_4);
        trier_num->setObjectName(QStringLiteral("trier_num"));
        trier_num->setGeometry(QRect(530, 60, 111, 20));
        trier_datee = new QRadioButton(tab_4);
        trier_datee->setObjectName(QStringLiteral("trier_datee"));
        trier_datee->setGeometry(QRect(400, 60, 111, 20));
        comboBox_modifier_ref = new QComboBox(tab_4);
        comboBox_modifier_ref->setObjectName(QStringLiteral("comboBox_modifier_ref"));
        comboBox_modifier_ref->setGeometry(QRect(592, 410, 81, 21));
        label_pic_3 = new QLabel(tab_4);
        label_pic_3->setObjectName(QStringLiteral("label_pic_3"));
        label_pic_3->setGeometry(QRect(30, 330, 191, 131));
        le_QR_2 = new QLineEdit(tab_4);
        le_QR_2->setObjectName(QStringLiteral("le_QR_2"));
        le_QR_2->setGeometry(QRect(310, 170, 31, 31));
        lineEdit_7 = new QPushButton(tab_4);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(320, 340, 93, 28));
        pb_upload = new QPushButton(tab_4);
        pb_upload->setObjectName(QStringLiteral("pb_upload"));
        pb_upload->setGeometry(QRect(590, 370, 93, 28));
        ajouterT = new QPushButton(tab_4);
        ajouterT->setObjectName(QStringLiteral("ajouterT"));
        ajouterT->setGeometry(QRect(212, 20, 101, 28));
        le_nomT = new QLineEdit(tab_4);
        le_nomT->setObjectName(QStringLiteral("le_nomT"));
        le_nomT->setGeometry(QRect(80, 140, 113, 22));
        le_prenomT = new QLineEdit(tab_4);
        le_prenomT->setObjectName(QStringLiteral("le_prenomT"));
        le_prenomT->setGeometry(QRect(80, 180, 113, 22));
        afficherT = new QPushButton(tab_4);
        afficherT->setObjectName(QStringLiteral("afficherT"));
        afficherT->setGeometry(QRect(212, 70, 101, 28));
        modifierT = new QPushButton(tab_4);
        modifierT->setObjectName(QStringLiteral("modifierT"));
        modifierT->setGeometry(QRect(212, 120, 101, 28));
        supprimerT = new QPushButton(tab_4);
        supprimerT->setObjectName(QStringLiteral("supprimerT"));
        supprimerT->setGeometry(QRect(82, 300, 101, 28));
        exporter_pdfT = new QPushButton(tab_4);
        exporter_pdfT->setObjectName(QStringLiteral("exporter_pdfT"));
        exporter_pdfT->setGeometry(QRect(650, 330, 75, 23));
        deconnexion_3 = new QPushButton(tab_4);
        deconnexion_3->setObjectName(QStringLiteral("deconnexion_3"));
        deconnexion_3->setGeometry(QRect(660, 430, 93, 28));
        tabWidget_2->addTab(tab_4, QString());
        label_27->raise();
        label_28->raise();
        label_29->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_pic_3->raise();
        lineEdit_7->raise();
        le_num->raise();
        le_ref->raise();
        le_date->raise();
        spinBox->raise();
        QR_code->raise();
        le_ref_supp->raise();
        recher_edit->raise();
        tab_ticket->raise();
        trier_nom->raise();
        trier_num->raise();
        trier_datee->raise();
        comboBox_modifier_ref->raise();
        le_QR_2->raise();
        pb_upload->raise();
        ajouterT->raise();
        le_nomT->raise();
        le_prenomT->raise();
        afficherT->raise();
        modifierT->raise();
        supprimerT->raise();
        exporter_pdfT->raise();
        deconnexion_3->raise();
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_34 = new QLabel(tab_5);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(-10, -20, 791, 491));
        label_34->setPixmap(QPixmap(QString::fromUtf8("../../../../bb.png")));
        label_34->setScaledContents(true);
        pushButton_stat = new QPushButton(tab_5);
        pushButton_stat->setObjectName(QStringLiteral("pushButton_stat"));
        pushButton_stat->setGeometry(QRect(320, 50, 111, 28));
        label_stat = new QLabel(tab_5);
        label_stat->setObjectName(QStringLiteral("label_stat"));
        label_stat->setGeometry(QRect(30, 110, 671, 331));
        tabWidget_2->addTab(tab_5, QString());
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        tabWidget_3 = new QTabWidget(page_6);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(20, 20, 1111, 521));
        tabWidget_3->setStyleSheet(QStringLiteral("background-color: rgb(216, 216, 216);"));
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        pb_ajouter_3 = new QPushButton(tab_6);
        pb_ajouter_3->setObjectName(QStringLiteral("pb_ajouter_3"));
        pb_ajouter_3->setGeometry(QRect(300, 40, 191, 28));
        pb_modifier_3 = new QPushButton(tab_6);
        pb_modifier_3->setObjectName(QStringLiteral("pb_modifier_3"));
        pb_modifier_3->setGeometry(QRect(300, 80, 191, 28));
        pb_supprimer_3 = new QPushButton(tab_6);
        pb_supprimer_3->setObjectName(QStringLiteral("pb_supprimer_3"));
        pb_supprimer_3->setGeometry(QRect(300, 120, 191, 28));
        pb_afficher_3 = new QPushButton(tab_6);
        pb_afficher_3->setObjectName(QStringLiteral("pb_afficher_3"));
        pb_afficher_3->setGeometry(QRect(300, 160, 191, 28));
        label_35 = new QLabel(tab_6);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(60, 80, 56, 16));
        label_36 = new QLabel(tab_6);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(60, 120, 56, 16));
        le_equipe1 = new QLineEdit(tab_6);
        le_equipe1->setObjectName(QStringLiteral("le_equipe1"));
        le_equipe1->setGeometry(QRect(150, 80, 113, 22));
        le_equipe2 = new QLineEdit(tab_6);
        le_equipe2->setObjectName(QStringLiteral("le_equipe2"));
        le_equipe2->setGeometry(QRect(150, 120, 113, 22));
        le_numero_2 = new QLabel(tab_6);
        le_numero_2->setObjectName(QStringLiteral("le_numero_2"));
        le_numero_2->setGeometry(QRect(60, 40, 56, 16));
        le_numero = new QLineEdit(tab_6);
        le_numero->setObjectName(QStringLiteral("le_numero"));
        le_numero->setGeometry(QRect(150, 40, 113, 22));
        le_reference = new QLineEdit(tab_6);
        le_reference->setObjectName(QStringLiteral("le_reference"));
        le_reference->setGeometry(QRect(150, 160, 113, 22));
        label_37 = new QLabel(tab_6);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(60, 160, 56, 16));
        tabCompetition = new QTableView(tab_6);
        tabCompetition->setObjectName(QStringLiteral("tabCompetition"));
        tabCompetition->setGeometry(QRect(20, 351, 711, 211));
        comboBox_3 = new QComboBox(tab_6);
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setGeometry(QRect(660, 330, 73, 22));
        trierTemps = new QRadioButton(tab_6);
        trierTemps->setObjectName(QStringLiteral("trierTemps"));
        trierTemps->setGeometry(QRect(580, 70, 97, 20));
        trier_score_2 = new QRadioButton(tab_6);
        trier_score_2->setObjectName(QStringLiteral("trier_score_2"));
        trier_score_2->setGeometry(QRect(710, 70, 131, 20));
        trier_equipe = new QRadioButton(tab_6);
        trier_equipe->setObjectName(QStringLiteral("trier_equipe"));
        trier_equipe->setGeometry(QRect(860, 70, 151, 20));
        tabrecherche = new QTableView(tab_6);
        tabrecherche->setObjectName(QStringLiteral("tabrecherche"));
        tabrecherche->setGeometry(QRect(760, 180, 331, 381));
        recherche = new QLineEdit(tab_6);
        recherche->setObjectName(QStringLiteral("recherche"));
        recherche->setGeometry(QRect(980, 160, 113, 22));
        score = new QLabel(tab_6);
        score->setObjectName(QStringLiteral("score"));
        score->setGeometry(QRect(60, 200, 56, 16));
        mail = new QLabel(tab_6);
        mail->setObjectName(QStringLiteral("mail"));
        mail->setGeometry(QRect(60, 240, 56, 16));
        le_score_2 = new QLineEdit(tab_6);
        le_score_2->setObjectName(QStringLiteral("le_score_2"));
        le_score_2->setGeometry(QRect(150, 200, 113, 22));
        le_mail = new QLineEdit(tab_6);
        le_mail->setObjectName(QStringLiteral("le_mail"));
        le_mail->setGeometry(QRect(150, 240, 113, 22));
        pushButton_11 = new QPushButton(tab_6);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(690, 20, 151, 28));
        pushButton_12 = new QPushButton(tab_6);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(320, 230, 151, 28));
        pushButton_13 = new QPushButton(tab_6);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(910, 120, 161, 28));
        pushButton_14 = new QPushButton(tab_6);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(320, 320, 161, 28));
        le_temps = new QLineEdit(tab_6);
        le_temps->setObjectName(QStringLiteral("le_temps"));
        le_temps->setGeometry(QRect(150, 280, 113, 22));
        temps = new QLabel(tab_6);
        temps->setObjectName(QStringLiteral("temps"));
        temps->setGeometry(QRect(60, 280, 56, 16));
        rechav = new QLineEdit(tab_6);
        rechav->setObjectName(QStringLiteral("rechav"));
        rechav->setGeometry(QRect(520, 330, 113, 22));
        rechavv = new QLabel(tab_6);
        rechavv->setObjectName(QStringLiteral("rechavv"));
        rechavv->setGeometry(QRect(520, 310, 111, 16));
        deconnexion_4 = new QPushButton(tab_6);
        deconnexion_4->setObjectName(QStringLiteral("deconnexion_4"));
        deconnexion_4->setGeometry(QRect(980, 10, 93, 28));
        tabWidget_3->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        pushButton_15 = new QPushButton(tab_7);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(770, 50, 151, 28));
        pushButton_16 = new QPushButton(tab_7);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(90, 50, 161, 28));
        lineEdit_to_email = new QLineEdit(tab_7);
        lineEdit_to_email->setObjectName(QStringLiteral("lineEdit_to_email"));
        lineEdit_to_email->setGeometry(QRect(120, 160, 331, 51));
        lineEdit_subject_email = new QLineEdit(tab_7);
        lineEdit_subject_email->setObjectName(QStringLiteral("lineEdit_subject_email"));
        lineEdit_subject_email->setGeometry(QRect(120, 280, 331, 51));
        label_38 = new QLabel(tab_7);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 180, 56, 16));
        label_39 = new QLabel(tab_7);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 300, 56, 16));
        label_40 = new QLabel(tab_7);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(20, 390, 56, 16));
        textEdit_email = new QTextEdit(tab_7);
        textEdit_email->setObjectName(QStringLiteral("textEdit_email"));
        textEdit_email->setGeometry(QRect(90, 380, 371, 141));
        tabWidget_3->addTab(tab_7, QString());
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        tabWidget_4 = new QTabWidget(page_7);
        tabWidget_4->setObjectName(QStringLiteral("tabWidget_4"));
        tabWidget_4->setGeometry(QRect(120, 70, 781, 431));
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        label_51 = new QLabel(tab_11);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(30, 50, 56, 16));
        label_52 = new QLabel(tab_11);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(30, 100, 56, 16));
        label_53 = new QLabel(tab_11);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(30, 150, 56, 16));
        label_54 = new QLabel(tab_11);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(30, 200, 111, 16));
        label_55 = new QLabel(tab_11);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(0, 0, 781, 411));
        label_55->setPixmap(QPixmap(QString::fromUtf8("../../../../../Desktop/bb.png")));
        label_55->setScaledContents(true);
        tableView = new QTableView(tab_11);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(360, 70, 381, 211));
        enterID = new QLineEdit(tab_11);
        enterID->setObjectName(QStringLiteral("enterID"));
        enterID->setGeometry(QRect(562, 360, 111, 31));
        lineEdit_nom = new QLineEdit(tab_11);
        lineEdit_nom->setObjectName(QStringLiteral("lineEdit_nom"));
        lineEdit_nom->setGeometry(QRect(340, 30, 111, 21));
        comboBox_4 = new QComboBox(tab_11);
        comboBox_4->setObjectName(QStringLiteral("comboBox_4"));
        comboBox_4->setGeometry(QRect(680, 30, 73, 22));
        pushButton_22 = new QPushButton(tab_11);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(10, 250, 101, 28));
        pushButton_23 = new QPushButton(tab_11);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(120, 250, 111, 28));
        pushButton_24 = new QPushButton(tab_11);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(260, 250, 93, 28));
        afficherE = new QPushButton(tab_11);
        afficherE->setObjectName(QStringLiteral("afficherE"));
        afficherE->setGeometry(QRect(414, 320, 101, 31));
        modifierE = new QPushButton(tab_11);
        modifierE->setObjectName(QStringLiteral("modifierE"));
        modifierE->setGeometry(QRect(254, 320, 81, 31));
        supprimerE = new QPushButton(tab_11);
        supprimerE->setObjectName(QStringLiteral("supprimerE"));
        supprimerE->setGeometry(QRect(570, 320, 81, 31));
        ajouterE = new QPushButton(tab_11);
        ajouterE->setObjectName(QStringLiteral("ajouterE"));
        ajouterE->setGeometry(QRect(100, 320, 81, 31));
        le_idE = new QLineEdit(tab_11);
        le_idE->setObjectName(QStringLiteral("le_idE"));
        le_idE->setGeometry(QRect(180, 50, 113, 20));
        le_nomE = new QLineEdit(tab_11);
        le_nomE->setObjectName(QStringLiteral("le_nomE"));
        le_nomE->setGeometry(QRect(180, 90, 113, 20));
        le_prenomE = new QLineEdit(tab_11);
        le_prenomE->setObjectName(QStringLiteral("le_prenomE"));
        le_prenomE->setGeometry(QRect(180, 140, 113, 20));
        le_emplacementE = new QLineEdit(tab_11);
        le_emplacementE->setObjectName(QStringLiteral("le_emplacementE"));
        le_emplacementE->setGeometry(QRect(180, 190, 113, 20));
        deconnexion_5 = new QPushButton(tab_11);
        deconnexion_5->setObjectName(QStringLiteral("deconnexion_5"));
        deconnexion_5->setGeometry(QRect(30, 360, 93, 28));
        tabWidget_4->addTab(tab_11, QString());
        label_51->raise();
        label_52->raise();
        label_53->raise();
        label_54->raise();
        label_55->raise();
        enterID->raise();
        comboBox_4->raise();
        pushButton_22->raise();
        pushButton_23->raise();
        pushButton_24->raise();
        tableView->raise();
        lineEdit_nom->raise();
        afficherE->raise();
        modifierE->raise();
        supprimerE->raise();
        ajouterE->raise();
        le_idE->raise();
        le_nomE->raise();
        le_prenomE->raise();
        le_emplacementE->raise();
        deconnexion_5->raise();
        tab_12 = new QWidget();
        tab_12->setObjectName(QStringLiteral("tab_12"));
        listView = new QListView(tab_12);
        listView->setObjectName(QStringLiteral("listView"));
        listView->setGeometry(QRect(5, 80, 451, 301));
        horizontalScrollBar = new QScrollBar(tab_12);
        horizontalScrollBar->setObjectName(QStringLiteral("horizontalScrollBar"));
        horizontalScrollBar->setGeometry(QRect(20, 350, 391, 20));
        horizontalScrollBar->setOrientation(Qt::Horizontal);
        verticalScrollBar = new QScrollBar(tab_12);
        verticalScrollBar->setObjectName(QStringLiteral("verticalScrollBar"));
        verticalScrollBar->setGeometry(QRect(430, 99, 20, 251));
        verticalScrollBar->setOrientation(Qt::Vertical);
        label_56 = new QLabel(tab_12);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(0, -5, 781, 411));
        label_56->setPixmap(QPixmap(QString::fromUtf8("../../../../../Desktop/bb.png")));
        label_56->setScaledContents(true);
        pushButton_25 = new QPushButton(tab_12);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(620, 260, 121, 28));
        export_pdfE = new QPushButton(tab_12);
        export_pdfE->setObjectName(QStringLiteral("export_pdfE"));
        export_pdfE->setGeometry(QRect(624, 310, 111, 31));
        tabWidget_4->addTab(tab_12, QString());
        label_56->raise();
        pushButton_25->raise();
        listView->raise();
        horizontalScrollBar->raise();
        verticalScrollBar->raise();
        export_pdfE->raise();
        stackedWidget->addWidget(page_7);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1305, 26));
        MainWindow->setMenuBar(menubar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(5);
        impression_badges->setCurrentIndex(1);
        tabWidget->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(0);
        tabWidget_4->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "nom d'utilisateur", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "mot de passe", Q_NULLPTR));
        connecter->setText(QApplication::translate("MainWindow", "se connecter", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "AUTHENTIFICATION", Q_NULLPTR));
        label_10->setText(QString());
        quitter->setText(QApplication::translate("MainWindow", "quitter", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("MainWindow", "login", Q_NULLPTR));
        label_7->setText(QString());
        label_11->setText(QString());
        impression_badges->setTabText(impression_badges->indexOf(tab_3), QApplication::translate("MainWindow", "S'authentifier", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "nom", Q_NULLPTR));
        pb_ajouter->setText(QApplication::translate("MainWindow", "ajouter", Q_NULLPTR));
        pb_modifier->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        pb_afficher->setText(QApplication::translate("MainWindow", "afficher", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "prenom", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "ann\303\251e de naissance", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "nationalit\303\251", Q_NULLPTR));
        pb_importer->setText(QApplication::translate("MainWindow", "impoter photo", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "type du sport", Q_NULLPTR));
        label_14->setText(QString());
        export_pdf->setText(QApplication::translate("MainWindow", "exporter PDF", Q_NULLPTR));
        calcul_score->setText(QApplication::translate("MainWindow", "calcul score", Q_NULLPTR));
        pb_supprimer->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        trier_prenom->setText(QApplication::translate("MainWindow", "trier prenom", Q_NULLPTR));
        trier_annees->setText(QApplication::translate("MainWindow", "trier annees naissance", Q_NULLPTR));
        trier_score->setText(QApplication::translate("MainWindow", "trier score ", Q_NULLPTR));
        lineEdit_5->setText(QString());
        label_15->setText(QString());
        label_16->setText(QApplication::translate("MainWindow", "equipe", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "score", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "equipe", Q_NULLPTR));
        label_score->setText(QApplication::translate("MainWindow", "score total: ", Q_NULLPTR));
        label_pdf->setText(QString());
        pushButton_7->setText(QApplication::translate("MainWindow", "imprimer", Q_NULLPTR));
        ajout_imag->setText(QApplication::translate("MainWindow", "ajouter image", Q_NULLPTR));
        deconnexion->setText(QApplication::translate("MainWindow", "deconnexion", Q_NULLPTR));
        impression_badges->setTabText(impression_badges->indexOf(tab), QApplication::translate("MainWindow", "gestion joueur", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "Liste des spectacles :", Q_NULLPTR));
        qb_ajouter->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        pb_supp->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        label_20->setText(QString());
        label_21->setText(QApplication::translate("MainWindow", "horaire", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "duree", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "Num", Q_NULLPTR));
        exporter->setText(QApplication::translate("MainWindow", "Exporter", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "Type", Q_NULLPTR));
        label_25->setText(QString());
        label_26->setText(QApplication::translate("MainWindow", "Trier par :", Q_NULLPTR));
        trie_horaire->setText(QApplication::translate("MainWindow", "Horaire", Q_NULLPTR));
        trie_duree->setText(QApplication::translate("MainWindow", "Duree", Q_NULLPTR));
        trie_type->setText(QApplication::translate("MainWindow", "Type", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        lineEdit_6->setText(QString());
        pushButton_10->setText(QApplication::translate("MainWindow", "afficher membre du spectacle", Q_NULLPTR));
        label_pic_2->setText(QString());
        deconnexion_1->setText(QApplication::translate("MainWindow", "deconnexion", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Les spectacles", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "datee", Q_NULLPTR));
        label_28->setText(QApplication::translate("MainWindow", "prenom", Q_NULLPTR));
        label_29->setText(QApplication::translate("MainWindow", "nomt", Q_NULLPTR));
        label_30->setText(QApplication::translate("MainWindow", "num", Q_NULLPTR));
        label_31->setText(QApplication::translate("MainWindow", "reference", Q_NULLPTR));
        QR_code->setText(QApplication::translate("MainWindow", "ajouter QR code", Q_NULLPTR));
        label_32->setText(QApplication::translate("MainWindow", "R\303\251f", Q_NULLPTR));
        label_33->setText(QString());
        trier_nom->setText(QApplication::translate("MainWindow", "trier par nom", Q_NULLPTR));
        trier_num->setText(QApplication::translate("MainWindow", "trier par num", Q_NULLPTR));
        trier_datee->setText(QApplication::translate("MainWindow", "trier pate date", Q_NULLPTR));
        label_pic_3->setText(QString());
        lineEdit_7->setText(QApplication::translate("MainWindow", "Chercher", Q_NULLPTR));
        pb_upload->setText(QApplication::translate("MainWindow", "upload", Q_NULLPTR));
        ajouterT->setText(QApplication::translate("MainWindow", "ajouter", Q_NULLPTR));
        afficherT->setText(QApplication::translate("MainWindow", "afficher", Q_NULLPTR));
        modifierT->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        supprimerT->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        exporter_pdfT->setText(QApplication::translate("MainWindow", "exporter", Q_NULLPTR));
        deconnexion_3->setText(QApplication::translate("MainWindow", "deconnexion", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QApplication::translate("MainWindow", "g\303\251rer ticket", Q_NULLPTR));
        label_34->setText(QString());
        pushButton_stat->setText(QApplication::translate("MainWindow", "STASTISTIQUE", Q_NULLPTR));
        label_stat->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QApplication::translate("MainWindow", "statistique", Q_NULLPTR));
        pb_ajouter_3->setText(QApplication::translate("MainWindow", "ajouter", Q_NULLPTR));
        pb_modifier_3->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        pb_supprimer_3->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        pb_afficher_3->setText(QApplication::translate("MainWindow", "afficher", Q_NULLPTR));
        label_35->setText(QApplication::translate("MainWindow", "equipe1", Q_NULLPTR));
        label_36->setText(QApplication::translate("MainWindow", "equipe2", Q_NULLPTR));
        le_numero_2->setText(QApplication::translate("MainWindow", "numero", Q_NULLPTR));
        label_37->setText(QApplication::translate("MainWindow", "reference", Q_NULLPTR));
        trierTemps->setText(QApplication::translate("MainWindow", "trier temps", Q_NULLPTR));
        trier_score_2->setText(QApplication::translate("MainWindow", "trier selon score", Q_NULLPTR));
        trier_equipe->setText(QApplication::translate("MainWindow", "trier selon equipe", Q_NULLPTR));
        score->setText(QApplication::translate("MainWindow", "score", Q_NULLPTR));
        mail->setText(QApplication::translate("MainWindow", "mail", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("MainWindow", "tri des competitions", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "ajouter un timeur", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("MainWindow", "chercher l'equipe gagnate", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("MainWindow", "statistique", Q_NULLPTR));
        temps->setText(QApplication::translate("MainWindow", "temps", Q_NULLPTR));
        rechavv->setText(QApplication::translate("MainWindow", "recherche avancee", Q_NULLPTR));
        deconnexion_4->setText(QApplication::translate("MainWindow", "deconnexion", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_6), QApplication::translate("MainWindow", "gestion du competition", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("MainWindow", "ajouter un timeur", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("MainWindow", "envoyer un mail ", Q_NULLPTR));
        label_38->setText(QApplication::translate("MainWindow", "email", Q_NULLPTR));
        label_39->setText(QApplication::translate("MainWindow", "objet", Q_NULLPTR));
        label_40->setText(QApplication::translate("MainWindow", "texte", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_7), QApplication::translate("MainWindow", "plus d'options", Q_NULLPTR));
        label_51->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        label_52->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        label_53->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        label_54->setText(QApplication::translate("MainWindow", "emplacement", Q_NULLPTR));
        label_55->setText(QString());
        enterID->setPlaceholderText(QApplication::translate("MainWindow", "entrer id", Q_NULLPTR));
        pushButton_22->setText(QApplication::translate("MainWindow", "trier par nom ", Q_NULLPTR));
        pushButton_23->setText(QApplication::translate("MainWindow", "trier par prenom", Q_NULLPTR));
        pushButton_24->setText(QApplication::translate("MainWindow", "trier par id", Q_NULLPTR));
        afficherE->setText(QApplication::translate("MainWindow", "afficher", Q_NULLPTR));
        modifierE->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        supprimerE->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        ajouterE->setText(QApplication::translate("MainWindow", "ajouter", Q_NULLPTR));
        deconnexion_5->setText(QApplication::translate("MainWindow", "deconnexion", Q_NULLPTR));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_11), QApplication::translate("MainWindow", "Employer", Q_NULLPTR));
        label_56->setText(QString());
        pushButton_25->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        export_pdfE->setText(QApplication::translate("MainWindow", "export pdf", Q_NULLPTR));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_12), QApplication::translate("MainWindow", "Notification", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
